packages:
  # the root package.json
  - '.'
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  #- 'packages/types'
  #- 'packages/core'
  #- 'packages/desktop'
  #- 'packages/webapp'
  #- 'packages/webcomponents'
  #- 'packages/services-ui-preact'
  #- 'packages/services-ui-react'
  #- 'packages/webpack-plugin-jst'
  #- 'packages/bundles'
  #- 'packages/server'
  #- 'packages/registry'
  #- 'components/**'
  # exclude packages that are inside test/ directories
  #- '!**/test/**'